### PR TITLE
Splitting up main into a test and publish phase

### PR DESCRIPTION
**Pull request by stjohnjohnson**
Since PRs are going to run the `main` job we shouldn't publish in there.

### CODE REVIEW

**Comment by nkatzman** [comment]
👍

**Comment by nkatzman** [comment]
whoops clicked the wrong button

**Comment by nkatzman** [comment]
We won't be able to publish anymore. That's okay for now?

**Comment by stjohnjohnson** [comment]
For now.  We'll have to create a new job to do so.

**Pull request merged**
